#!/usr/bin/env python3
"""Genera el esquema PostgreSQL a partir de SCHEMA.sql.

SCHEMA.sql sigue siendo la ÚNICA fuente del esquema. Mantener a mano un segundo
fichero en dialecto Postgres sería garantizar que un día dejen de coincidir, y
esa divergencia ya nos costó un rato en la Fase 1.

    python3 pg_schema.py            # lo imprime
    python3 pg_schema.py --check    # avisa de lo que no sabe traducir
"""
from __future__ import annotations

import re
import sys

import core

# Lo que cambia en el DDL entre los dos motores.
#   AUTOINCREMENT  -> IDENTITY (el estándar; SERIAL es la forma antigua)
#   REAL           -> DOUBLE PRECISION
#   COLLATE NOCASE -> no existe: se resuelve con un índice sobre lower(columna),
#                     que es como se hace la unicidad sin mayúsculas en Postgres
_TIPOS = (
    (r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
     "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
    (r"\bREAL\b", "DOUBLE PRECISION"),
    (r"\s+COLLATE\s+NOCASE", ""),
)

# Columnas que en SQLite eran COLLATE NOCASE: su unicidad pasa a un índice
# funcional. Sin esto, 'Ana@x.com' y 'ana@x.com' serían dos cuentas distintas.
_SIN_MAYUSCULAS = {"users": ("username", "email")}


def _traducir_tabla(ddl: str) -> str:
    for patron, nuevo in _TIPOS:
        ddl = re.sub(patron, nuevo, ddl, flags=re.I)
    ddl = core.a_postgres(ddl)
    # a_postgres convierte los '?' en '%s', pero en el DDL no hay ninguno; si
    # apareciera, es que el esquema tiene algo raro.
    return ddl


def generar() -> str:
    with open(core.SCHEMA_PATH, "r", encoding="utf-8") as fh:
        texto = fh.read()

    salida = [
        "-- GENERADO por pg_schema.py desde SCHEMA.sql. No editar a mano.",
        "-- La fuente del esquema es SCHEMA.sql; este fichero es su traducción.",
        "",
    ]
    # tablas, en el orden en que aparecen: respeta las claves ajenas
    for m in re.finditer(r"CREATE TABLE IF NOT EXISTS (\w+)\s*\(.*?\n\);", texto, re.S):
        tabla = m.group(1)
        salida.append(_traducir_tabla(m.group(0)))
        for col in _SIN_MAYUSCULAS.get(tabla, ()):
            salida.append(
                f"CREATE UNIQUE INDEX IF NOT EXISTS idx_{tabla}_{col}_lower\n"
                f"    ON {tabla} (lower({col}));")
        salida.append("")
    # indices
    for m in re.finditer(r"CREATE INDEX IF NOT EXISTS .*?;", texto, re.S):
        salida.append(re.sub(r"\s+", " ", m.group(0)))
    return "\n".join(salida) + "\n"


def sentencias() -> list[str]:
    """El esquema troceado en sentencias ejecutables, sin comentarios.

    Vive aquí y no en cada script porque la primera versión de este troceado
    descartaba los bloques que EMPEZABAN por un comentario, y con ellos se fue
    la tabla users entera -- sin dar error, porque nunca llegó a ejecutarse.
    """
    fuera = []
    for trozo in re.split(r";\s*\n", generar()):
        # quita las líneas de comentario del principio, no el trozo completo
        lineas = [l for l in trozo.split("\n")
                  if not l.strip().startswith("--")]
        limpio = "\n".join(lineas).strip()
        if limpio:
            fuera.append(limpio)
    return fuera


def comprobar(ddl: str) -> int:
    """Avisa de restos de dialecto SQLite que no supe traducir."""
    sospechas = [
        ("AUTOINCREMENT", "AUTOINCREMENT"),
        ("COLLATE NOCASE", "COLLATE NOCASE"),
        ("date('now'", "funciones de fecha de SQLite"),
        ("datetime('now'", "funciones de fecha de SQLite"),
        ("IFNULL", "IFNULL"),
        (" REAL", "tipo REAL"),
        ("%s", "placeholder en el DDL"),
    ]
    problemas = [aviso for marca, aviso in sospechas if marca in ddl]
    for p in sorted(set(problemas)):
        print("SIN TRADUCIR: " + p, file=sys.stderr)
    return 1 if problemas else 0


if __name__ == "__main__":
    ddl = generar()
    if "--check" in sys.argv:
        codigo = comprobar(ddl)
        s = sentencias()
        print("tablas: %d  |  indices: %d  |  sentencias: %d"
              % (ddl.count("CREATE TABLE"), ddl.count("CREATE INDEX"), len(s)))
        # cada sentencia tiene que ser ejecutable: si alguna quedó vacía o sin
        # su CREATE, el troceado se comió algo
        huecos = [x[:40] for x in s if not re.match(r"CREATE (TABLE|INDEX|UNIQUE)", x)]
        for h in huecos:
            print("SENTENCIA RARA: " + h, file=sys.stderr)
        raise SystemExit(1 if (huecos or codigo) else 0)
    print(ddl)
