"""
seed_decks.py — Puebla los decks de aprendizaje ESTÁTICOS (tipo Refold).

El contenido (palabras, frases, traducciones) está escrito a mano/curado aquí (no
consume la cuota de Gemini). El audio se pre-genera con `say` (voz Samantha, EE.UU.,
ritmo lento) y se guarda; la app siempre lo lee desde la base + los .wav.

Uso:
    python seed_decks.py          # siembra el LOTE DE PRUEBA (por defecto)
    python seed_decks.py --full   # (futuro) siembra los sets completos

Es idempotente: re-ejecutar no duplica (INSERT OR IGNORE por deck+front).
"""

# Copyright (C) 2026 Marco Antonio Garcia
#
# Este archivo es parte de este proyecto, software libre bajo la GNU Affero
# General Public License v3 o posterior. Se distribuye SIN NINGUNA GARANTÍA.
# Ver el archivo LICENSE para los términos completos.

from __future__ import annotations

import os
import sys

import core

# --------------------------------------------------------------------------- #
# LOTE DE PRUEBA — contenido curado (se ampliará a los sets completos luego).
# Cada tarjeta: (front [lo que se escucha], traducción, nota/ejemplo)
# --------------------------------------------------------------------------- #
WORDS = [
    ("because", "porque", "I'm tired because I didn't sleep. — Estoy cansado porque no dormí."),
    ("always", "siempre", "She is always on time. — Ella siempre llega a tiempo."),
    ("understand", "entender", "I don't understand this word. — No entiendo esta palabra."),
    ("important", "importante", "This is very important. — Esto es muy importante."),
    ("enough", "suficiente", "That's enough for today. — Es suficiente por hoy."),
    ("already", "ya", "I have already finished. — Ya terminé."),
    ("people", "gente / personas", "Many people came. — Vino mucha gente."),
    ("time", "tiempo / vez", "I don't have time. — No tengo tiempo."),
    ("year", "año", "See you next year. — Nos vemos el próximo año."),
    ("day", "día", "Have a nice day. — Que tengas buen día."),
    ("way", "manera / camino", "This is the best way. — Esta es la mejor manera."),
    ("thing", "cosa", "One more thing. — Una cosa más."),
    ("world", "mundo", "The whole world knows. — El mundo entero lo sabe."),
    ("life", "vida", "That's life. — Así es la vida."),
    ("hand", "mano", "Give me your hand. — Dame la mano."),
    ("place", "lugar", "This is a nice place. — Este es un lugar bonito."),
    ("week", "semana", "See you next week. — Nos vemos la próxima semana."),
    ("home", "casa / hogar", "I'm going home. — Me voy a casa."),
    ("water", "agua", "I need water. — Necesito agua."),
    ("room", "habitación / cuarto", "Clean your room. — Limpia tu cuarto."),
    ("money", "dinero", "I have no money. — No tengo dinero."),
    ("friend", "amigo / amiga", "She's my best friend. — Es mi mejor amiga."),
    ("family", "familia", "I love my family. — Amo a mi familia."),
    ("food", "comida", "The food is great. — La comida está buenísima."),
    ("city", "ciudad", "I live in the city. — Vivo en la ciudad."),
    ("country", "país", "What country are you from? — ¿De qué país eres?"),
    ("problem", "problema", "No problem. — No hay problema."),
    ("question", "pregunta", "Good question. — Buena pregunta."),
    ("name", "nombre", "What's your name? — ¿Cómo te llamas?"),
    ("night", "noche", "Good night. — Buenas noches."),
    ("morning", "mañana", "Good morning. — Buenos días."),
    ("book", "libro", "I'm reading a book. — Estoy leyendo un libro."),
    ("word", "palabra", "What does this word mean? — ¿Qué significa esta palabra?"),
    ("good", "bueno", "This is good. — Esto está bueno."),
    ("bad", "malo", "That's bad news. — Son malas noticias."),
    ("new", "nuevo", "I have a new phone. — Tengo un teléfono nuevo."),
    ("old", "viejo / antiguo", "This house is old. — Esta casa es vieja."),
    ("big", "grande", "It's a big house. — Es una casa grande."),
    ("small", "pequeño", "A small problem. — Un problema pequeño."),
    ("first", "primero", "You're first. — Eres el primero."),
    ("last", "último", "The last one. — El último."),
    ("long", "largo", "It's a long way. — Es un camino largo."),
    ("great", "genial / grandioso", "That's great! — ¡Qué genial!"),
    ("right", "correcto / derecho", "You're right. — Tienes razón."),
    ("different", "diferente", "It's different. — Es diferente."),
    ("easy", "fácil", "It's easy. — Es fácil."),
    ("hard", "difícil / duro", "It's hard. — Es difícil."),
    ("happy", "feliz / contento", "I'm happy. — Estoy feliz."),
    ("sad", "triste", "She looks sad. — Se ve triste."),
    ("beautiful", "hermoso / bonito", "What a beautiful day. — Qué día tan hermoso."),
    ("really", "de verdad / realmente", "Really? — ¿En serio?"),
    ("very", "muy", "It's very cold. — Hace mucho frío."),
    ("just", "solo / apenas", "I just arrived. — Acabo de llegar."),
    ("only", "solo / únicamente", "Only you. — Solo tú."),
    ("now", "ahora", "Do it now. — Hazlo ahora."),
    ("here", "aquí", "Come here. — Ven aquí."),
    ("there", "allí / ahí", "Over there. — Por allá."),
    ("again", "otra vez / de nuevo", "Try again. — Inténtalo otra vez."),
    ("today", "hoy", "What's today? — ¿Qué día es hoy?"),
    ("tomorrow", "mañana", "See you tomorrow. — Nos vemos mañana."),
    ("yesterday", "ayer", "I saw her yesterday. — La vi ayer."),
    ("maybe", "quizás / tal vez", "Maybe later. — Quizás después."),
    ("sure", "seguro / claro", "Are you sure? — ¿Estás seguro?"),
    ("together", "juntos", "We did it together. — Lo hicimos juntos."),
    ("man", "hombre", "That man is tall. — Ese hombre es alto."),
    ("woman", "mujer", "She is a kind woman. — Es una mujer amable."),
    ("child", "niño / niña", "The child is sleeping. — El niño está durmiendo."),
    ("boy", "niño / chico", "The boy is playing. — El niño está jugando."),
    ("girl", "niña / chica", "The girl is reading. — La niña está leyendo."),
    ("mother", "madre", "My mother cooks well. — Mi madre cocina bien."),
    ("father", "padre", "His father works here. — Su padre trabaja aquí."),
    ("brother", "hermano", "I have one brother. — Tengo un hermano."),
    ("sister", "hermana", "Her sister is a nurse. — Su hermana es enfermera."),
    ("job", "trabajo / empleo", "I love my job. — Amo mi trabajo."),
    ("school", "escuela", "She goes to school. — Ella va a la escuela."),
    ("teacher", "maestro / profesor", "He is a teacher. — Es maestro."),
    ("student", "estudiante", "I'm a student. — Soy estudiante."),
    ("doctor", "doctor / médico", "Call a doctor. — Llama a un médico."),
    ("car", "auto / coche", "My car is new. — Mi coche es nuevo."),
    ("phone", "teléfono", "Where's my phone? — ¿Dónde está mi teléfono?"),
    ("house", "casa", "They bought a house. — Compraron una casa."),
    ("door", "puerta", "Close the door. — Cierra la puerta."),
    ("street", "calle", "The street is busy. — La calle está concurrida."),
    ("music", "música", "I love music. — Amo la música."),
    ("movie", "película", "Let's watch a movie. — Veamos una película."),
    ("game", "juego / partido", "Good game. — Buen partido."),
    ("idea", "idea", "Good idea! — ¡Buena idea!"),
    ("love", "amor / amar", "Love is important. — El amor es importante."),
    ("health", "salud", "Health comes first. — La salud es lo primero."),
    ("body", "cuerpo", "Take care of your body. — Cuida tu cuerpo."),
    ("face", "cara / rostro", "Wash your face. — Lávate la cara."),
    ("mind", "mente", "It's on my mind. — Lo tengo en la mente."),
    ("language", "idioma / lengua", "English is a language. — El inglés es un idioma."),
    ("color", "color", "What's your favorite color? — ¿Cuál es tu color favorito?"),
    ("sun", "sol", "The sun is bright. — El sol brilla."),
    ("rain", "lluvia", "I like the rain. — Me gusta la lluvia."),
    ("weather", "clima / tiempo", "Nice weather today. — Buen clima hoy."),
    ("young", "joven", "She is young. — Es joven."),
    ("tall", "alto", "He is very tall. — Es muy alto."),
    ("fast", "rápido", "That car is fast. — Ese coche es rápido."),
    ("slow", "lento", "The internet is slow. — El internet está lento."),
    ("hot", "caliente / caluroso", "The coffee is hot. — El café está caliente."),
    ("cold", "frío", "It's cold outside. — Hace frío afuera."),
    ("warm", "cálido / templado", "A warm day. — Un día cálido."),
    ("clean", "limpio", "The room is clean. — El cuarto está limpio."),
    ("dirty", "sucio", "My shoes are dirty. — Mis zapatos están sucios."),
    ("full", "lleno", "The glass is full. — El vaso está lleno."),
    ("empty", "vacío", "The box is empty. — La caja está vacía."),
    ("open", "abierto / abrir", "The store is open. — La tienda está abierta."),
    ("strong", "fuerte", "She is strong. — Ella es fuerte."),
    ("weak", "débil", "I feel weak. — Me siento débil."),
    ("expensive", "caro", "It's too expensive. — Es demasiado caro."),
    ("cheap", "barato", "It's cheap. — Es barato."),
    ("safe", "seguro", "You're safe here. — Aquí estás seguro."),
    ("free", "libre / gratis", "Are you free tonight? — ¿Estás libre esta noche?"),
    ("busy", "ocupado", "I'm busy now. — Estoy ocupado ahora."),
    ("tired", "cansado", "I'm tired. — Estoy cansado."),
    ("hungry", "con hambre", "I'm hungry. — Tengo hambre."),
    ("thirsty", "con sed", "I'm thirsty. — Tengo sed."),
    ("ready", "listo", "Are you ready? — ¿Estás listo?"),
    ("sick", "enfermo", "She is sick. — Está enferma."),
    ("funny", "gracioso / divertido", "That's funny. — Qué gracioso."),
    ("quiet", "callado / silencioso", "Be quiet. — Guarda silencio."),
    ("dark", "oscuro", "It's dark. — Está oscuro."),
    ("wrong", "incorrecto / mal", "Something is wrong. — Algo está mal."),
    ("possible", "posible", "Is it possible? — ¿Es posible?"),
    ("soon", "pronto", "See you soon. — Hasta pronto."),
    ("often", "a menudo", "I often walk. — Camino a menudo."),
    ("sometimes", "a veces", "Sometimes I read. — A veces leo."),
    ("usually", "normalmente", "I usually wake up early. — Normalmente despierto temprano."),
    ("almost", "casi", "I'm almost done. — Casi termino."),
    ("too", "demasiado / también", "It's too much. — Es demasiado."),
    ("about", "acerca de / sobre", "It's about love. — Es sobre el amor."),
    ("everything", "todo", "Everything is fine. — Todo está bien."),
    ("something", "algo", "Say something. — Di algo."),
    ("nothing", "nada", "There's nothing here. — No hay nada aquí."),
    ("someone", "alguien", "Someone called. — Alguien llamó."),
    ("everyone", "todos", "Everyone is here. — Todos están aquí."),
    ("nobody", "nadie", "Nobody knows. — Nadie sabe."),
    ("who", "quién", "Who is it? — ¿Quién es?"),
    ("what", "qué", "What is this? — ¿Qué es esto?"),
    ("where", "dónde", "Where are you? — ¿Dónde estás?"),
    ("why", "por qué", "Why not? — ¿Por qué no?"),
    ("how", "cómo", "How are you? — ¿Cómo estás?"),
    ("which", "cuál / qué", "Which one? — ¿Cuál?"),
    ("table", "mesa", "Put it on the table. — Ponlo en la mesa."),
    ("chair", "silla", "Sit in the chair. — Siéntate en la silla."),
    ("window", "ventana", "Open the window. — Abre la ventana."),
    ("bed", "cama", "I'm in bed. — Estoy en la cama."),
    ("kitchen", "cocina", "She's in the kitchen. — Está en la cocina."),
    ("bathroom", "baño", "Where's the bathroom? — ¿Dónde está el baño?"),
    ("floor", "piso / suelo", "It's on the floor. — Está en el suelo."),
    ("wall", "pared", "A picture on the wall. — Un cuadro en la pared."),
    ("key", "llave", "I lost my key. — Perdí mi llave."),
    ("bag", "bolsa / bolso", "Where's my bag? — ¿Dónde está mi bolsa?"),
    ("wallet", "cartera / billetera", "I forgot my wallet. — Olvidé mi cartera."),
    ("clothes", "ropa", "New clothes. — Ropa nueva."),
    ("shoe", "zapato", "My shoe is untied. — Mi zapato está desatado."),
    ("shirt", "camisa", "A blue shirt. — Una camisa azul."),
    ("coffee", "café", "I want coffee. — Quiero café."),
    ("tea", "té", "A cup of tea. — Una taza de té."),
    ("bread", "pan", "Fresh bread. — Pan fresco."),
    ("milk", "leche", "We need milk. — Necesitamos leche."),
    ("egg", "huevo", "One egg, please. — Un huevo, por favor."),
    ("fruit", "fruta", "Eat fruit. — Come fruta."),
    ("apple", "manzana", "An apple a day. — Una manzana al día."),
    ("meat", "carne", "I don't eat meat. — No como carne."),
    ("rice", "arroz", "Rice with chicken. — Arroz con pollo."),
    ("restaurant", "restaurante", "A nice restaurant. — Un buen restaurante."),
    ("store", "tienda", "The store is closed. — La tienda está cerrada."),
    ("hospital", "hospital", "He's in the hospital. — Está en el hospital."),
    ("office", "oficina", "I work at the office. — Trabajo en la oficina."),
    ("airport", "aeropuerto", "Meet me at the airport. — Vernos en el aeropuerto."),
    ("hotel", "hotel", "A cheap hotel. — Un hotel barato."),
    ("bank", "banco", "I'm at the bank. — Estoy en el banco."),
    ("park", "parque", "Let's go to the park. — Vamos al parque."),
    ("beach", "playa", "A day at the beach. — Un día en la playa."),
    ("mountain", "montaña", "We climbed the mountain. — Subimos la montaña."),
    ("river", "río", "The river is long. — El río es largo."),
    ("sea", "mar", "The sea is blue. — El mar es azul."),
    ("road", "carretera / camino", "A long road. — Un camino largo."),
    ("garden", "jardín", "A beautiful garden. — Un jardín hermoso."),
    ("clock", "reloj", "The clock is slow. — El reloj está atrasado."),
    ("picture", "foto / imagen", "Take a picture. — Toma una foto."),
    ("gift", "regalo", "A nice gift. — Un lindo regalo."),
    ("news", "noticias", "Good news. — Buenas noticias."),
    ("plan", "plan", "What's the plan? — ¿Cuál es el plan?"),
    ("meeting", "reunión", "I have a meeting. — Tengo una reunión."),
    ("party", "fiesta", "A birthday party. — Una fiesta de cumpleaños."),
    ("trip", "viaje", "Have a nice trip. — Buen viaje."),
    ("ticket", "boleto / entrada", "Two tickets, please. — Dos boletos, por favor."),
    ("reason", "razón / motivo", "There's no reason. — No hay razón."),
    ("result", "resultado", "The result is clear. — El resultado es claro."),
    ("chance", "oportunidad", "Give me a chance. — Dame una oportunidad."),
    ("example", "ejemplo", "For example. — Por ejemplo."),
    ("fact", "hecho", "In fact. — De hecho."),
    ("truth", "verdad", "Tell the truth. — Di la verdad."),
    ("mistake", "error", "My mistake. — Mi error."),
    ("dream", "sueño", "A nice dream. — Un lindo sueño."),
    ("future", "futuro", "In the future. — En el futuro."),
    ("past", "pasado", "In the past. — En el pasado."),
    ("simple", "simple / sencillo", "Keep it simple. — Hazlo sencillo."),
    ("clear", "claro", "Is it clear? — ¿Está claro?"),
    ("certain", "cierto / seguro", "I'm certain. — Estoy seguro."),
    ("common", "común", "It's very common. — Es muy común."),
    ("special", "especial", "A special day. — Un día especial."),
    ("real", "real / verdadero", "Is it real? — ¿Es real?"),
    ("similar", "similar / parecido", "They look similar. — Se parecen."),
    ("several", "varios", "Several times. — Varias veces."),
    ("human", "humano", "A human being. — Un ser humano."),
    ("natural", "natural", "It's natural. — Es natural."),
    ("personal", "personal", "It's personal. — Es personal."),
    ("public", "público", "In public. — En público."),
    ("private", "privado", "A private room. — Una habitación privada."),
    ("general", "general", "In general. — En general."),
    ("final", "final", "The final answer. — La respuesta final."),
    ("recent", "reciente", "Recent news. — Noticias recientes."),
    ("modern", "moderno", "A modern house. — Una casa moderna."),
    ("popular", "popular", "A popular song. — Una canción popular."),
    ("famous", "famoso", "A famous actor. — Un actor famoso."),
    ("serious", "serio", "Are you serious? — ¿Hablas en serio?"),
    ("loud", "ruidoso / fuerte", "The music is loud. — La música está fuerte."),
    ("soft", "suave", "A soft pillow. — Una almohada suave."),
    ("deep", "profundo", "Deep water. — Agua profunda."),
    ("wide", "ancho", "A wide street. — Una calle ancha."),
    ("thin", "delgado / fino", "A thin book. — Un libro delgado."),
    ("thick", "grueso", "A thick wall. — Una pared gruesa."),
    ("straight", "recto / derecho", "Go straight. — Sigue derecho."),
    ("round", "redondo", "A round table. — Una mesa redonda."),
    ("flat", "plano", "A flat surface. — Una superficie plana."),
    ("dangerous", "peligroso", "It's dangerous. — Es peligroso."),
    ("less", "menos", "Less is more. — Menos es más."),
    ("more", "más", "I want more. — Quiero más."),
    ("most", "la mayoría / más", "Most people agree. — La mayoría está de acuerdo."),
    ("still", "todavía / aún", "I'm still here. — Todavía estoy aquí."),
    ("yet", "todavía / ya", "Not yet. — Todavía no."),
    ("ago", "hace (tiempo)", "Two days ago. — Hace dos días."),
    ("own", "propio", "My own room. — Mi propia habitación."),
    ("able", "capaz", "I'm able to help. — Soy capaz de ayudar."),
    # --- ampliación: alta frecuencia (sustantivos y palabras muy usadas) ---
    ("number", "número", "What's your number? — ¿Cuál es tu número?"),
    ("part", "parte", "It's part of the plan. — Es parte del plan."),
    ("group", "grupo", "We work in a group. — Trabajamos en grupo."),
    ("company", "empresa / compañía", "She works for a big company. — Trabaja en una gran empresa."),
    ("story", "historia / cuento", "Tell me the story. — Cuéntame la historia."),
    ("point", "punto", "That's a good point. — Es un buen punto."),
    ("area", "área / zona", "It's a quiet area. — Es una zona tranquila."),
    ("case", "caso", "In that case, let's go. — En ese caso, vamos."),
    ("government", "gobierno", "The government decided. — El gobierno decidió."),
    ("service", "servicio", "The service was great. — El servicio fue excelente."),
    ("system", "sistema", "The system is down. — El sistema está caído."),
    ("information", "información", "I need more information. — Necesito más información."),
    ("business", "negocio", "Business is good. — El negocio va bien."),
    ("hour", "hora", "I'll be there in an hour. — Estaré ahí en una hora."),
    ("minute", "minuto", "Wait a minute. — Espera un minuto."),
    ("month", "mes", "See you next month. — Nos vemos el próximo mes."),
    ("moment", "momento", "One moment, please. — Un momento, por favor."),
    ("side", "lado", "The other side. — El otro lado."),
    ("kind", "tipo / clase", "What kind of music? — ¿Qué tipo de música?"),
    ("end", "final / fin", "At the end of the day. — Al final del día."),
    ("order", "orden / pedido", "Can I take your order? — ¿Le tomo su pedido?"),
    ("level", "nivel", "My English level is B1. — Mi nivel de inglés es B1."),
    ("power", "poder / energía", "The power went out. — Se fue la luz."),
    ("history", "historia", "I love history. — Me encanta la historia."),
    ("science", "ciencia", "She studies science. — Ella estudia ciencia."),
    ("nature", "naturaleza", "I love nature. — Me encanta la naturaleza."),
    ("society", "sociedad", "Modern society. — La sociedad moderna."),
    ("market", "mercado", "The job market. — El mercado laboral."),
    ("price", "precio", "What's the price? — ¿Cuál es el precio?"),
    ("value", "valor", "Good value for money. — Buena relación calidad-precio."),
    ("quality", "calidad", "High quality. — Alta calidad."),
    ("experience", "experiencia", "A great experience. — Una gran experiencia."),
    ("opportunity", "oportunidad", "A great opportunity. — Una gran oportunidad."),
    ("situation", "situación", "A difficult situation. — Una situación difícil."),
    ("effect", "efecto", "It had no effect. — No tuvo efecto."),
    ("effort", "esfuerzo", "Make an effort. — Haz un esfuerzo."),
    ("energy", "energía", "I have no energy. — No tengo energía."),
    ("attention", "atención", "Pay attention. — Presta atención."),
    ("memory", "memoria / recuerdo", "A good memory. — Buena memoria."),
    ("feeling", "sentimiento / sensación", "A strange feeling. — Una sensación extraña."),
    ("sense", "sentido", "It makes sense. — Tiene sentido."),
    ("voice", "voz", "In a low voice. — En voz baja."),
    ("sound", "sonido", "A loud sound. — Un sonido fuerte."),
    ("light", "luz", "Turn on the light. — Enciende la luz."),
    ("air", "aire", "Fresh air. — Aire fresco."),
    ("fire", "fuego / incendio", "The house is on fire. — La casa se incendia."),
    ("ground", "suelo / tierra", "On the ground. — En el suelo."),
    ("tree", "árbol", "A tall tree. — Un árbol alto."),
    ("animal", "animal", "My favorite animal. — Mi animal favorito."),
    ("dog", "perro", "I have a dog. — Tengo un perro."),
    ("cat", "gato", "The cat is sleeping. — El gato está durmiendo."),
    ("baby", "bebé", "The baby is crying. — El bebé está llorando."),
    ("person", "persona", "A nice person. — Una persona agradable."),
    ("team", "equipo", "We're a team. — Somos un equipo."),
    ("boss", "jefe", "My boss is nice. — Mi jefe es amable."),
    ("customer", "cliente", "The customer is waiting. — El cliente está esperando."),
    ("class", "clase", "I have an English class. — Tengo clase de inglés."),
    ("lesson", "lección", "Today's lesson. — La lección de hoy."),
    ("message", "mensaje", "I got your message. — Recibí tu mensaje."),
    ("computer", "computadora", "My computer is slow. — Mi computadora es lenta."),
    ("glass", "vaso / vidrio", "A glass of water. — Un vaso de agua."),
    ("everybody", "todos", "Everybody knows it. — Todos lo saben."),
    ("anything", "algo / cualquier cosa", "Do you need anything? — ¿Necesitas algo?"),
    ("anyone", "alguien / cualquiera", "Is anyone home? — ¿Hay alguien en casa?"),
    ("both", "ambos / los dos", "I like both. — Me gustan los dos."),
    ("each", "cada", "Each person. — Cada persona."),
    ("every", "cada / todos", "Every day. — Todos los días."),
]

PHRASES = [
    ("How's it going?", "¿Cómo te va?", ""),
    ("I'll be right back.", "Ahora vuelvo.", ""),
    ("It doesn't matter.", "No importa.", ""),
    ("What do you mean?", "¿A qué te refieres?", ""),
    ("I'm looking forward to it.", "Tengo muchas ganas de eso.", ""),
    ("Can you give me a hand?", "¿Me puedes echar una mano?", ""),
    ("Never mind.", "Olvídalo. / No importa.", ""),
    ("It's up to you.", "Tú decides. / Depende de ti.", ""),
    ("See you later.", "Nos vemos luego.", ""),
    ("Thank you so much.", "Muchísimas gracias.", ""),
    ("You're welcome.", "De nada.", ""),
    ("Excuse me.", "Disculpa. / Con permiso.", ""),
    ("I'm sorry.", "Lo siento.", ""),
    ("No worries.", "No te preocupes.", ""),
    ("Take care.", "Cuídate.", ""),
    ("Good luck.", "Buena suerte.", ""),
    ("I don't know.", "No sé.", ""),
    ("I think so.", "Creo que sí.", ""),
    ("Me too.", "Yo también.", ""),
    ("Not at all.", "Para nada. / En absoluto.", ""),
    ("Hold on.", "Espera. / Un momento.", ""),
    ("Let me see.", "Déjame ver.", ""),
    ("Sounds good.", "Suena bien.", ""),
    ("Of course.", "Por supuesto.", ""),
    ("Are you okay?", "¿Estás bien?", ""),
    ("What's up?", "¿Qué tal? / ¿Qué onda?", ""),
    ("How much is it?", "¿Cuánto cuesta?", ""),
    ("I have no idea.", "No tengo idea.", ""),
    ("Just a moment.", "Un momento.", ""),
    ("Let's go.", "Vámonos.", ""),
    ("That makes sense.", "Tiene sentido.", ""),
    ("I agree.", "Estoy de acuerdo.", ""),
    ("It depends.", "Depende.", ""),
    ("Don't worry.", "No te preocupes.", ""),
    ("Good job.", "Buen trabajo.", ""),
    # --- ampliación: presentarse y conversar ---
    ("Nice to meet you.", "Mucho gusto / Encantado de conocerte.", ""),
    ("How are you?", "¿Cómo estás?", ""),
    ("I'm fine, thanks.", "Estoy bien, gracias.", ""),
    ("What's your name?", "¿Cómo te llamas?", ""),
    ("Where are you from?", "¿De dónde eres?", ""),
    ("Could you repeat that?", "¿Podrías repetir eso?", ""),
    ("I don't understand.", "No entiendo.", ""),
    ("Could you speak more slowly?", "¿Podrías hablar más despacio?", ""),
    ("What time is it?", "¿Qué hora es?", ""),
    ("How do you say this in English?", "¿Cómo se dice esto en inglés?", ""),
    ("Let me know.", "Avísame.", ""),
    ("No problem.", "No hay problema.", ""),
    ("Here you are.", "Aquí tienes.", ""),
    ("Congratulations!", "¡Felicidades!", ""),
    ("Long time no see.", "Cuánto tiempo sin verte.", ""),
    ("I'm not sure.", "No estoy seguro.", ""),
    ("I'd love to.", "Me encantaría.", ""),
    ("That's a good idea.", "Es una buena idea.", ""),
    ("Well done.", "Bien hecho.", ""),
    ("Maybe next time.", "Quizá la próxima vez.", ""),
    # --- Tiendas y compras -------------------------------------------------
    ("Do you have this in a different size?", "¿Lo tienen en otra talla?", "Tiendas"),
    ("I'm just looking, thanks.", "Solo estoy mirando, gracias.", "Tiendas"),
    ("Can I try this on?", "¿Me lo puedo probar?", "Tiendas"),
    ("Where are the fitting rooms?", "¿Dónde están los probadores?", "Tiendas"),
    ("Is this on sale?", "¿Esto está en oferta?", "Tiendas"),
    ("Do you take card?", "¿Aceptan tarjeta?", "Tiendas"),
    ("Can I pay in cash?", "¿Puedo pagar en efectivo?", "Tiendas"),
    ("Could I get a receipt, please?", "¿Me da un recibo, por favor?", "Tiendas"),
    ("I'd like to return this.", "Quisiera devolver esto.", "Tiendas"),
    ("Do you have it in stock?", "¿Lo tienen disponible?", "Tiendas"),
    ("That's a bit too expensive for me.", "Es un poco caro para mí.", "Tiendas"),
    ("I'll take it.", "Me lo llevo.", "Tiendas"),
    ("Could you gift-wrap it?", "¿Me lo puede envolver para regalo?", "Tiendas"),
    ("Are you in line?", "¿Está haciendo fila?", "Tiendas"),
    ("Keep the change.", "Quédese con el cambio.", "Tiendas"),
    # --- Restaurantes y cafés ----------------------------------------------
    ("A table for two, please.", "Una mesa para dos, por favor.", "Restaurante"),
    ("Could we see the menu?", "¿Nos trae la carta?", "Restaurante"),
    ("What do you recommend?", "¿Qué me recomienda?", "Restaurante"),
    ("I'll have the same.", "Yo quiero lo mismo.", "Restaurante"),
    ("Is this spicy?", "¿Esto pica?", "Restaurante"),
    ("I'm allergic to nuts.", "Soy alérgico a los frutos secos.", "Restaurante"),
    ("Could I get this to go?", "¿Me lo puede poner para llevar?", "Restaurante"),
    ("Could we get the bill, please?", "¿Nos trae la cuenta, por favor?", "Restaurante"),
    ("Can we split the bill?", "¿Podemos dividir la cuenta?", "Restaurante"),
    ("This isn't what I ordered.", "Esto no es lo que pedí.", "Restaurante"),
    # --- Direcciones y transporte -------------------------------------------
    ("How do I get to the station?", "¿Cómo llego a la estación?", "Direcciones"),
    ("Is it within walking distance?", "¿Se puede ir andando?", "Direcciones"),
    ("I think I'm lost.", "Creo que me perdí.", "Direcciones"),
    ("Which line should I take?", "¿Qué línea tengo que tomar?", "Transporte"),
    ("Does this bus go downtown?", "¿Este autobús va al centro?", "Transporte"),
    ("How long does it take?", "¿Cuánto tiempo se tarda?", "Transporte"),
    ("Could you let me know when we get there?", "¿Me avisa cuando lleguemos?", "Transporte"),
    ("I'd like a one-way ticket.", "Quisiera un billete de ida.", "Transporte"),
    # --- Viajes y hotel -----------------------------------------------------
    ("I have a reservation under my name.", "Tengo una reserva a mi nombre.", "Hotel"),
    ("What time is check-out?", "¿A qué hora hay que dejar la habitación?", "Hotel"),
    ("Could I leave my luggage here?", "¿Puedo dejar aquí mi equipaje?", "Hotel"),
    ("Is breakfast included?", "¿El desayuno está incluido?", "Hotel"),
    ("The Wi-Fi isn't working.", "El wifi no funciona.", "Hotel"),
    # --- Teléfono y citas ---------------------------------------------------
    ("Could I speak to Ana, please?", "¿Puedo hablar con Ana, por favor?", "Teléfono"),
    ("I'm calling about the appointment.", "Llamo por la cita.", "Teléfono"),
    ("Can I call you back later?", "¿Te puedo llamar más tarde?", "Teléfono"),
    ("You're breaking up.", "Se te corta la llamada.", "Teléfono"),
    ("I'd like to make an appointment.", "Quisiera pedir una cita.", "Citas"),
    ("Something came up.", "Me surgió algo.", "Citas"),
    ("Can we reschedule?", "¿Podemos cambiar la fecha?", "Citas"),
    ("I'm running late.", "Voy con retraso.", "Citas"),
    ("Does Thursday work for you?", "¿Te viene bien el jueves?", "Citas"),
    # --- Trabajo y reuniones ------------------------------------------------
    ("Can we go over this again?", "¿Podemos repasarlo otra vez?", "Trabajo"),
    ("I'll get back to you on that.", "Te contesto sobre eso.", "Trabajo"),
    ("Let's touch base tomorrow.", "Hablamos mañana para ponernos al día.", "Trabajo"),
    ("I'm on it.", "Me pongo con ello.", "Trabajo"),
    ("That's out of scope for now.", "Eso queda fuera del alcance por ahora.", "Trabajo"),
    ("I'll keep you posted.", "Te voy contando.", "Trabajo"),
    ("Let me double-check.", "Déjame comprobarlo.", "Trabajo"),
    # --- Conversación real (mantener el hilo) -------------------------------
    ("How was your weekend?", "¿Qué tal el fin de semana?", "Conversación"),
    ("What have you been up to?", "¿Qué has estado haciendo?", "Conversación"),
    ("Same here.", "Igual yo.", "Conversación"),
    ("Tell me about it.", "¡Dímelo a mí! (estoy de acuerdo)", "Conversación"),
    ("That sounds rough.", "Suena duro.", "Conversación"),
    ("Good for you!", "¡Me alegro por ti!", "Conversación"),
    ("Wait, really?", "Espera, ¿en serio?", "Conversación"),
    ("I know what you mean.", "Sé a qué te refieres.", "Conversación"),
    ("Sorry, I didn't catch that.", "Perdona, no te entendí.", "Conversación"),
    ("What's it like?", "¿Cómo es?", "Conversación"),
    ("I'd rather not.", "Prefiero no hacerlo.", "Conversación"),
    ("It's not a big deal.", "No es para tanto.", "Conversación"),
    ("Let's catch up soon.", "A ver si nos ponemos al día pronto.", "Conversación"),
    ("I have to run.", "Me tengo que ir.", "Conversación"),
]

PHRASAL = [
    ("give up", "rendirse", "Don't give up. — No te rindas."),
    ("find out", "averiguar / descubrir", "I need to find out the truth. — Necesito averiguar la verdad."),
    ("look for", "buscar", "I'm looking for my keys. — Estoy buscando mis llaves."),
    ("run out of", "quedarse sin", "We ran out of milk. — Nos quedamos sin leche."),
    ("put off", "posponer", "Don't put off your homework. — No pospongas la tarea."),
    ("figure out", "resolver / entender", "I can't figure it out. — No logro entenderlo."),
    ("get along", "llevarse bien", "They get along well. — Se llevan bien."),
    ("show up", "aparecer / presentarse", "He didn't show up. — No apareció."),
    ("turn on", "encender", "Turn on the light. — Enciende la luz."),
    ("turn off", "apagar", "Turn off the TV. — Apaga la tele."),
    ("wake up", "despertarse", "I wake up at seven. — Me despierto a las siete."),
    ("get up", "levantarse", "Get up! — ¡Levántate!"),
    ("sit down", "sentarse", "Please sit down. — Por favor siéntate."),
    ("stand up", "ponerse de pie", "Stand up. — Ponte de pie."),
    ("come back", "regresar", "Come back soon. — Regresa pronto."),
    ("go back", "volver", "I want to go back. — Quiero volver."),
    ("pick up", "recoger / contestar", "Pick up the phone. — Contesta el teléfono."),
    ("put on", "ponerse (ropa)", "Put on your coat. — Ponte el abrigo."),
    ("take off", "quitarse / despegar", "Take off your shoes. — Quítate los zapatos."),
    ("look up", "buscar (información)", "Look it up online. — Búscalo en internet."),
    ("look after", "cuidar", "Look after the kids. — Cuida a los niños."),
    ("grow up", "crecer", "I grew up here. — Crecí aquí."),
    ("give back", "devolver", "Give it back. — Devuélvelo."),
    ("throw away", "tirar / botar", "Throw it away. — Tíralo."),
    ("work out", "ejercitarse / resolverse", "It worked out. — Salió bien."),
    ("calm down", "calmarse", "Calm down. — Cálmate."),
    ("hurry up", "apurarse", "Hurry up! — ¡Apúrate!"),
    ("check out", "revisar / echar un vistazo", "Check this out. — Mira esto."),
    ("hang out", "pasar el rato", "Let's hang out. — Salgamos a pasar el rato."),
    ("break up", "terminar (una relación)", "They broke up. — Terminaron."),
    ("carry on", "continuar", "Carry on. — Continúa."),
    ("set up", "configurar / montar", "Set up the account. — Configura la cuenta."),
    ("bring up", "mencionar / criar", "Don't bring that up. — No menciones eso."),
    ("come up with", "idear / proponer", "She came up with a plan. — Ideó un plan."),
    ("get back to", "responder a alguien", "I'll get back to you. — Te respondo luego."),
    # --- ampliación: los más comunes que faltaban ---
    ("get on", "subir(se) (a un transporte)", "Get on the bus. — Súbete al autobús."),
    ("get off", "bajar(se) (de un transporte)", "I get off at the next stop. — Me bajo en la próxima parada."),
    ("turn up", "subir (volumen) / aparecer", "Turn up the music. — Sube la música."),
    ("turn down", "bajar (volumen) / rechazar", "Turn down the TV. — Baja la tele."),
    ("put up with", "aguantar / tolerar", "I can't put up with the noise. — No aguanto el ruido."),
    ("take care of", "cuidar / encargarse de", "I'll take care of it. — Yo me encargo."),
    ("go on", "continuar / seguir", "Go on, I'm listening. — Sigue, te escucho."),
    ("end up", "terminar / acabar (haciendo algo)", "We ended up staying home. — Terminamos quedándonos en casa."),
    ("run into", "encontrarse (por casualidad)", "I ran into an old friend. — Me encontré a un viejo amigo."),
    ("sort out", "resolver / arreglar", "Let's sort this out. — Vamos a resolver esto."),
    # --- añadidos: phrasal verbs B1-B2 ------------------------------------
    ("look forward to", "tener ganas de / esperar con ilusión", "I look forward to the weekend. — Tengo ganas de que llegue el fin de semana."),
    ("get rid of", "deshacerse de", "We need to get rid of this old sofa. — Necesitamos deshacernos de este sofá viejo."),
    ("keep up with", "seguir el ritmo de", "I can't keep up with the news. — No puedo seguir el ritmo de las noticias."),
    ("come across", "encontrarse por casualidad", "I came across an old photo. — Me encontré con una foto antigua."),
    ("call off", "cancelar", "They called off the meeting. — Cancelaron la reunión."),
    ("turn out", "resultar", "It turned out to be a great idea. — Resultó ser una gran idea."),
    ("point out", "señalar", "She pointed out my mistake. — Señaló mi error."),
    ("fill out", "rellenar (un formulario)", "Please fill out this form. — Por favor, rellena este formulario."),
    ("take over", "hacerse cargo / tomar el control", "She will take over the project. — Ella se hará cargo del proyecto."),
    ("give in", "ceder", "He finally gave in. — Al final cedió."),
    ("go through", "pasar por / revisar", "We went through a hard time. — Pasamos por una época difícil."),
    ("put away", "guardar", "Put away your things, please. — Guarda tus cosas, por favor."),
    ("look into", "investigar", "I'll look into the problem. — Investigaré el problema."),
    ("catch up", "ponerse al día", "Let's catch up over coffee. — Pongámonos al día con un café."),
    ("move on", "pasar página / seguir adelante", "It's time to move on. — Es hora de pasar página."),
    ("cut down on", "reducir", "I'm cutting down on sugar. — Estoy reduciendo el azúcar."),
    ("get over", "superar", "It took months to get over the flu. — Tardé meses en superar la gripe."),
    ("let down", "decepcionar", "I don't want to let you down. — No quiero decepcionarte."),
    ("take up", "empezar (una afición)", "She took up painting last year. — Empezó a pintar el año pasado."),
    ("show off", "presumir", "He likes to show off his new car. — Le gusta presumir de su coche nuevo."),
]

# Verbos: front = "base, pasado, participio" (se leen las 3 formas). note = ejemplo.
VERBS = [
    # --- irregulares (los más usados) ---
    ("be, was, been", "ser / estar", "I have been here before. — He estado aquí antes."),
    ("have, had, had", "tener / haber", "She has had a long day. — Ha tenido un día largo."),
    ("do, did, done", "hacer", "I have done my work. — He hecho mi trabajo."),
    ("say, said, said", "decir", "He said hello. — Dijo hola."),
    ("go, went, gone", "ir", "They have gone home. — Se han ido a casa."),
    ("get, got, gotten", "conseguir / obtener", "I got a new job. — Conseguí un trabajo nuevo."),
    ("make, made, made", "hacer", "She made a cake. — Hizo un pastel."),
    ("know, knew, known", "saber / conocer", "I knew the answer. — Sabía la respuesta."),
    ("think, thought, thought", "pensar", "I thought about it. — Lo pensé."),
    ("take, took, taken", "tomar / llevar", "He took the bus. — Tomó el autobús."),
    ("see, saw, seen", "ver", "I have seen that movie. — He visto esa película."),
    ("come, came, come", "venir", "She came late. — Llegó tarde."),
    ("give, gave, given", "dar", "They gave me a gift. — Me dieron un regalo."),
    ("find, found, found", "encontrar", "I found my keys. — Encontré mis llaves."),
    ("tell, told, told", "decir / contar", "He told me the truth. — Me dijo la verdad."),
    ("become, became, become", "convertirse", "She became a doctor. — Se convirtió en doctora."),
    ("leave, left, left", "dejar / salir", "I left early. — Salí temprano."),
    ("feel, felt, felt", "sentir", "I felt tired. — Me sentí cansado."),
    ("bring, brought, brought", "traer", "She brought food. — Trajo comida."),
    ("begin, began, begun", "empezar", "The show has begun. — El espectáculo ha empezado."),
    ("keep, kept, kept", "mantener / guardar", "Keep the change. — Quédate con el cambio."),
    ("write, wrote, written", "escribir", "He wrote a letter. — Escribió una carta."),
    ("hear, heard, heard", "oír", "I heard a noise. — Oí un ruido."),
    ("let, let, let", "dejar / permitir", "Let me help. — Déjame ayudar."),
    ("mean, meant, meant", "significar", "What did you mean? — ¿Qué quisiste decir?"),
    ("meet, met, met", "conocer / reunirse", "We met yesterday. — Nos conocimos ayer."),
    ("run, ran, run", "correr", "She ran fast. — Corrió rápido."),
    ("pay, paid, paid", "pagar", "I paid the bill. — Pagué la cuenta."),
    ("speak, spoke, spoken", "hablar", "He has spoken. — Ha hablado."),
    ("buy, bought, bought", "comprar", "I bought a book. — Compré un libro."),
    ("eat, ate, eaten", "comer", "Have you eaten? — ¿Has comido?"),
    ("put, put, put", "poner", "Put it here. — Ponlo aquí."),
    # --- regulares (los más usados) ---
    ("want, wanted, wanted", "querer", "I wanted to help. — Quería ayudar."),
    ("need, needed, needed", "necesitar", "I need water. — Necesito agua."),
    ("use, used, used", "usar", "I used your pen. — Usé tu pluma."),
    ("work, worked, worked", "trabajar", "She worked late. — Trabajó hasta tarde."),
    ("call, called, called", "llamar", "He called me. — Me llamó."),
    ("try, tried, tried", "intentar", "I tried my best. — Hice lo mejor que pude."),
    ("ask, asked, asked", "preguntar / pedir", "She asked a question. — Hizo una pregunta."),
    ("help, helped, helped", "ayudar", "They helped us. — Nos ayudaron."),
    ("talk, talked, talked", "hablar / platicar", "We talked for hours. — Hablamos por horas."),
    ("start, started, started", "empezar", "It started to rain. — Empezó a llover."),
    ("like, liked, liked", "gustar", "I liked the food. — Me gustó la comida."),
    ("live, lived, lived", "vivir", "I lived in Mexico. — Viví en México."),
    ("believe, believed, believed", "creer", "I believe you. — Te creo."),
    ("happen, happened, happened", "pasar / suceder", "What happened? — ¿Qué pasó?"),
    ("change, changed, changed", "cambiar", "Things changed. — Las cosas cambiaron."),
    ("watch, watched, watched", "ver / mirar", "I watched a show. — Vi un programa."),
    ("follow, followed, followed", "seguir", "Follow me. — Sígueme."),
    ("stop, stopped, stopped", "parar / detener", "The car stopped. — El coche se detuvo."),
    ("open, opened, opened", "abrir", "She opened the door. — Abrió la puerta."),
    ("walk, walked, walked", "caminar", "We walked home. — Caminamos a casa."),
    ("learn, learned, learned", "aprender", "I learned a lot. — Aprendí mucho."),
    ("study, studied, studied", "estudiar", "He studied all night. — Estudió toda la noche."),
    # --- ampliación: irregulares muy usados ---
    ("understand, understood, understood", "entender", "Now I understand. — Ahora entiendo."),
    ("sit, sat, sat", "sentarse", "Please sit down. — Por favor siéntate."),
    ("stand, stood, stood", "estar de pie / pararse", "I stood in line. — Hice fila."),
    ("win, won, won", "ganar", "We won the game. — Ganamos el partido."),
    ("lose, lost, lost", "perder", "Don't lose it. — No lo pierdas."),
    ("send, sent, sent", "enviar", "I sent the email. — Envié el correo."),
    ("spend, spent, spent", "gastar / pasar (tiempo)", "I spent too much. — Gasté demasiado."),
    ("build, built, built", "construir", "They built a house. — Construyeron una casa."),
    ("hold, held, held", "sostener / sujetar", "Hold this, please. — Sostén esto, por favor."),
    ("break, broke, broken", "romper", "I broke my phone. — Rompí mi teléfono."),
    ("drive, drove, driven", "manejar / conducir", "She drove to work. — Manejó al trabajo."),
    ("grow, grew, grown", "crecer / cultivar", "Kids grow fast. — Los niños crecen rápido."),
    ("teach, taught, taught", "enseñar", "She taught me English. — Me enseñó inglés."),
    ("catch, caught, caught", "atrapar / tomar", "Catch the ball. — Atrapa la pelota."),
    ("choose, chose, chosen", "elegir", "You choose. — Tú eliges."),
    ("sleep, slept, slept", "dormir", "I slept well. — Dormí bien."),
    ("wear, wore, worn", "usar / llevar puesto", "She wore a red dress. — Llevaba un vestido rojo."),
    ("forget, forgot, forgotten", "olvidar", "Don't forget. — No lo olvides."),
    # --- ampliación: regulares muy usados ---
    ("decide, decided, decided", "decidir", "I decided to stay. — Decidí quedarme."),
    ("remember, remembered, remembered", "recordar", "I don't remember. — No recuerdo."),
    ("explain, explained, explained", "explicar", "Let me explain. — Déjame explicar."),
    ("wait, waited, waited", "esperar", "Wait for me. — Espérame."),
    ("show, showed, shown", "mostrar", "Show me how. — Muéstrame cómo."),
    ("move, moved, moved", "mover(se) / mudarse", "We moved to Madrid. — Nos mudamos a Madrid."),
    ("enjoy, enjoyed, enjoyed", "disfrutar", "Enjoy your meal. — Disfruta tu comida."),
    ("stay, stayed, stayed", "quedarse", "Stay here. — Quédate aquí."),
]

CONNECTORS = [
    ("and", "y", "Bread and butter. — Pan y mantequilla."),
    ("but", "pero", "I'm tired, but happy. — Estoy cansado, pero feliz."),
    ("because", "porque", "I left because it was late. — Me fui porque era tarde."),
    ("so", "así que / entonces", "It rained, so we stayed. — Llovió, así que nos quedamos."),
    ("however", "sin embargo", "It's hard; however, it's worth it. — Es difícil; sin embargo, vale la pena."),
    ("although", "aunque", "Although it's cold, I'll go. — Aunque hace frío, iré."),
    ("therefore", "por lo tanto", "He was late; therefore, he missed it. — Llegó tarde; por lo tanto, se lo perdió."),
    ("also", "también", "I also want one. — Yo también quiero uno."),
    ("then", "entonces / luego", "First eat, then rest. — Primero come, luego descansa."),
    ("while", "mientras", "I read while she cooks. — Leo mientras ella cocina."),
    ("if", "si", "Call me if you can. — Llámame si puedes."),
    ("when", "cuando", "I'll come when I'm ready. — Vendré cuando esté listo."),
    ("before", "antes (de)", "Wash your hands before eating. — Lávate las manos antes de comer."),
    ("after", "después (de)", "We left after lunch. — Nos fuimos después del almuerzo."),
    ("for example", "por ejemplo", "I like fruit, for example apples. — Me gusta la fruta, por ejemplo las manzanas."),
    ("in fact", "de hecho", "In fact, I agree. — De hecho, estoy de acuerdo."),
    ("of course", "por supuesto", "Of course I'll help. — Por supuesto que ayudaré."),
    ("instead", "en vez / en su lugar", "Let's walk instead. — Mejor caminemos."),
    ("besides", "además", "Besides, it's free. — Además, es gratis."),
    ("finally", "finalmente / por fin", "Finally, we arrived. — Por fin llegamos."),
    ("on the other hand", "por otro lado", "On the other hand, it's cheaper. — Por otro lado, es más barato."),
    ("even though", "aunque / a pesar de que", "Even though it's late, I'm awake. — Aunque es tarde, estoy despierto."),
    ("as a result", "como resultado", "As a result, we won. — Como resultado, ganamos."),
    ("by the way", "por cierto", "By the way, thanks. — Por cierto, gracias."),
    ("anyway", "de todos modos", "Anyway, let's continue. — De todos modos, sigamos."),
    ("such as", "tal como / como", "Sports such as soccer. — Deportes como el fútbol."),
    # --- ampliación ---
    ("moreover", "además / es más", "It's cheap; moreover, it's good. — Es barato; además, es bueno."),
    ("otherwise", "de lo contrario / si no", "Hurry, otherwise we'll be late. — Apúrate, si no llegaremos tarde."),
    ("that's why", "por eso", "It rained; that's why we stayed. — Llovió; por eso nos quedamos."),
    ("unless", "a menos que", "I won't go unless you come. — No iré a menos que vengas."),
    ("since", "ya que / desde", "Since it's late, let's stop. — Ya que es tarde, paremos."),
    ("meanwhile", "mientras tanto", "Meanwhile, I'll cook. — Mientras tanto, cocinaré."),
    ("whereas", "mientras que", "I like tea, whereas she likes coffee. — Me gusta el té, mientras que a ella el café."),
    ("in order to", "para / con el fin de", "I study in order to learn. — Estudio para aprender."),
    # --- añadidos: conectores B1-B2 ---------------------------------------
    ("as soon as", "en cuanto / tan pronto como", "Call me as soon as you arrive. — Llámame en cuanto llegues."),
    ("in addition", "además", "In addition, the price includes breakfast. — Además, el precio incluye el desayuno."),
    ("nevertheless", "no obstante", "It was late; nevertheless, she kept working. — Era tarde; no obstante, siguió trabajando."),
    ("despite", "a pesar de", "We went out despite the rain. — Salimos a pesar de la lluvia."),
    ("rather than", "en vez de", "I walked rather than took the bus. — Caminé en vez de tomar el autobús."),
    ("so that", "para que", "Speak slowly so that everyone understands. — Habla despacio para que todos entiendan."),
    ("as long as", "siempre que / mientras", "You can stay as long as you help. — Puedes quedarte siempre que ayudes."),
    ("actually", "en realidad", "It looks hard, but actually it's easy. — Parece difícil, pero en realidad es fácil."),
    ("eventually", "con el tiempo / al final", "He eventually found a job. — Con el tiempo encontró trabajo."),
    ("furthermore", "es más / además", "Furthermore, the data supports it. — Es más, los datos lo respaldan."),
    ("consequently", "en consecuencia", "He missed the train; consequently, he was late. — Perdió el tren; en consecuencia, llegó tarde."),
    ("whenever", "siempre que / cuando sea", "Call me whenever you need help. — Llámame siempre que necesites ayuda."),
    ("as well as", "además de", "She speaks French as well as English. — Habla francés además de inglés."),
    ("apart from", "aparte de", "Apart from the noise, the flat is perfect. — Aparte del ruido, el piso es perfecto."),
    ("due to", "debido a", "The flight was cancelled due to the storm. — El vuelo se canceló debido a la tormenta."),
    ("in the end", "al final", "In the end, we decided to stay. — Al final, decidimos quedarnos."),
    ("first of all", "antes que nada", "First of all, let me explain. — Antes que nada, déjame explicar."),
    ("what's more", "es más", "It's cheap; what's more, it works well. — Es barato; es más, funciona bien."),
    ("no matter what", "pase lo que pase", "I'll support you no matter what. — Te apoyaré pase lo que pase."),
    ("at least", "al menos", "At least we tried. — Al menos lo intentamos."),
]

VOCAB = [
    # Comida y bebida
    ("breakfast", "desayuno", "I had eggs for breakfast. — Desayuné huevos."),
    ("lunch", "almuerzo / comida", "Let's have lunch. — Vamos a almorzar."),
    ("dinner", "cena", "Dinner is ready. — La cena está lista."),
    ("water", "agua", "A glass of water, please. — Un vaso de agua, por favor."),
    ("chicken", "pollo", "I'll have the chicken. — Yo quiero el pollo."),
    ("vegetables", "verduras", "Eat your vegetables. — Cómete las verduras."),
    ("dessert", "postre", "What's for dessert? — ¿Qué hay de postre?"),
    ("spicy", "picante", "This food is spicy. — Esta comida está picante."),
    # Viajes
    ("airport", "aeropuerto", "I'm at the airport. — Estoy en el aeropuerto."),
    ("flight", "vuelo", "My flight is delayed. — Mi vuelo está retrasado."),
    ("luggage", "equipaje", "Where's my luggage? — ¿Dónde está mi equipaje?"),
    ("ticket", "boleto", "Here's your ticket. — Aquí está tu boleto."),
    ("hotel", "hotel", "We booked a hotel. — Reservamos un hotel."),
    ("map", "mapa", "Check the map. — Revisa el mapa."),
    ("abroad", "en el extranjero", "She lives abroad. — Vive en el extranjero."),
    # Trabajo / escuela
    ("meeting", "reunión", "I have a meeting at noon. — Tengo una reunión al mediodía."),
    ("deadline", "fecha límite", "The deadline is Friday. — La fecha límite es el viernes."),
    ("salary", "salario / sueldo", "A good salary. — Un buen sueldo."),
    ("colleague", "colega / compañero", "She's my colleague. — Es mi colega."),
    ("skill", "habilidad", "A useful skill. — Una habilidad útil."),
    ("homework", "tarea", "Do your homework. — Haz tu tarea."),
    # Emociones
    ("happy", "feliz / contento", "I'm so happy. — Estoy muy feliz."),
    ("angry", "enojado", "Don't be angry. — No te enojes."),
    ("scared", "asustado", "I was scared. — Estaba asustado."),
    ("bored", "aburrido", "I'm bored. — Estoy aburrido."),
    ("excited", "emocionado", "I'm excited about the trip. — Estoy emocionado por el viaje."),
    ("worried", "preocupado", "Don't be worried. — No te preocupes."),
    ("proud", "orgulloso", "I'm proud of you. — Estoy orgulloso de ti."),
    # Salud / cuerpo
    ("headache", "dolor de cabeza", "I have a headache. — Tengo dolor de cabeza."),
    ("medicine", "medicina", "Take your medicine. — Toma tu medicina."),
    ("rest", "descanso / descansar", "You need rest. — Necesitas descanso."),
    ("sick", "enfermo", "I feel sick. — Me siento enfermo."),
    # Casa / cotidiano
    ("neighbor", "vecino", "My neighbor is friendly. — Mi vecino es amable."),
    ("clean", "limpiar / limpio", "I need to clean the house. — Necesito limpiar la casa."),
    ("busy", "ocupado", "I'm really busy today. — Estoy muy ocupado hoy."),
    ("cheap", "barato", "It was really cheap. — Estaba muy barato."),
    ("expensive", "caro", "That's too expensive. — Eso es muy caro."),
    ("weather", "clima", "The weather is nice. — El clima está agradable."),
    ("weekend", "fin de semana", "Have a great weekend. — Que tengas buen fin de semana."),
    ("advice", "consejo", "Can I give you some advice? — ¿Te puedo dar un consejo?"),
    # Familia
    ("husband", "esposo", "Her husband is a teacher. — Su esposo es maestro."),
    ("wife", "esposa", "My wife loves music. — A mi esposa le encanta la música."),
    ("son", "hijo", "Their son is five. — Su hijo tiene cinco años."),
    ("daughter", "hija", "My daughter is at school. — Mi hija está en la escuela."),
    ("cousin", "primo / prima", "My cousin lives abroad. — Mi primo vive en el extranjero."),
    ("grandmother", "abuela", "I visit my grandmother. — Visito a mi abuela."),
    ("grandfather", "abuelo", "My grandfather is 80. — Mi abuelo tiene 80."),
    # Tecnología
    ("password", "contraseña", "I forgot my password. — Olvidé mi contraseña."),
    ("battery", "batería / pila", "My battery is low. — Mi batería está baja."),
    ("charger", "cargador", "Where's my charger? — ¿Dónde está mi cargador?"),
    ("screen", "pantalla", "The screen is broken. — La pantalla está rota."),
    ("file", "archivo", "Send me the file. — Envíame el archivo."),
    ("website", "sitio web", "Check the website. — Revisa el sitio web."),
    # Compras / trámites
    ("receipt", "recibo / ticket", "Keep the receipt. — Guarda el recibo."),
    ("cash", "efectivo", "I'll pay in cash. — Pagaré en efectivo."),
    ("discount", "descuento", "Is there a discount? — ¿Hay descuento?"),
    ("size", "talla / tamaño", "What size do you need? — ¿Qué talla necesitas?"),
    ("appointment", "cita", "I have an appointment. — Tengo una cita."),
    ("address", "dirección", "What's your address? — ¿Cuál es tu dirección?"),
    ("umbrella", "paraguas", "Take an umbrella. — Lleva un paraguas."),
]

# Las frases atadas a un ESCENARIO (tienda, restaurante, hotel…) van al mazo de
# situaciones, no al de frases cotidianas: "Frases cotidianas" son las sociales,
# las que sirven en cualquier conversación. Mezclarlas hacía que un mazo creciera
# sin criterio y que el otro se quedara siendo solo listas de palabras sueltas.
_ESCENARIOS = {"Tiendas", "Restaurante", "Direcciones", "Transporte", "Hotel",
               "Teléfono", "Citas", "Trabajo"}
PHRASES_SOCIAL = [c for c in PHRASES if (c[2] or "") not in _ESCENARIOS]
VOCAB_SITUACIONES = VOCAB + [c for c in PHRASES if (c[2] or "") in _ESCENARIOS]

DECKS = [
    ("words", "Palabras esenciales", "Las palabras más usadas del inglés.", WORDS),
    ("vocab", "Situaciones",
     "Palabras Y frases por escenario: tienda, restaurante, aeropuerto, hotel, teléfono, trabajo.",
     VOCAB_SITUACIONES),
    ("phrases", "Frases cotidianas",
     "Frases sociales que sirven en cualquier conversación.", PHRASES_SOCIAL),
    ("phrasal", "Phrasal verbs", "Los phrasal verbs más comunes.", PHRASAL),
    ("verbs", "Verbos esenciales", "Verbos más usados (irregulares y regulares) con sus formas.", VERBS),
    ("connectors", "Conectores", "Palabras que conectan ideas (linkers).", CONNECTORS),
]


def seed() -> None:
    db = core.DatabaseManager()
    for order, (key, name, desc, cards) in enumerate(DECKS):
        deck_id = db.ensure_deck(key, name, desc, lang="en", sort_order=order)
        for pos, (front, translation, third) in enumerate(cards):
            # El tercer campo es el EJEMPLO ("inglés — español"). Si no lleva el
            # separador y es una etiqueta corta, es la situación de uso
            # ("Tiendas"): va a 'category', no a 'note'. Meterla en 'note' hacía
            # que la tarjeta mostrara "Tiendas" donde debía ir el ejemplo.
            es_categoria = third and "—" not in third and len(third.split()) <= 2
            note = "" if es_categoria else third
            category = third if es_categoria else ""
            # El audio se genera on-demand vía /api/tts (voz Piper elegida), y se cachea.
            db.add_deck_card(deck_id, pos, front, translation, note, None, category)
        print(f"[{name}] {len(cards)} tarjetas ✓")
    print("Siembra completada.")


if __name__ == "__main__":
    if "--full" in sys.argv:
        print("Sets completos: pendientes (se agregarán tras validar el lote de prueba).")
    seed()
